# kubectl create serviceaccount myserviceaccount
# for older a token is created automatically when a service account is created
# 

# #new way
# kubectl create token myserviceaccount

# doing this the old way 
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  annotations:
    kubernetes.io/service-account.name: myserviceaccount